### ISSUE TITLE
Create table labs

### ISSUE THREAD

**Issue by fp2020nulp** [FP2020-Practical-Course/labs-assessment#4]
Create table `labs` where assessed and validated labs should be stored:
```
Table: labs
Columns:
  email: type=string
  lab_id: type=int
  file: type=byte
```

Create table script should be located under `/sql-scripts/` project directory

Use database setup done in #5
